version : "3"

networks:
  test:
    external:
      name: test
services: 
  nodeapp:
    deploy:
      placement:
        constraints:
            - node.labels.name == manager
    image: stefanklinger/node-app:1.0
    ports :
      - 4000:4000
    networks:
      test:
        aliases:
          - nodeapp
