name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: false

channels:
  - channelName: mychannel
    contracts:
    - id: basic

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/f836cd98c8cdd5f6387d02b37b81edbc5cf0c2ec29c83765f1f85eabb26f2feb_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org1.yaml'
      discover: true

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/89f4fcd40f87208e5cb960a715346036c2b76a8b76fa6bc43adeb614d9c48afc_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org2.yaml'
      discover: true

  - mspid: Org3MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/f785a4441c28b48c0740f0d7d043ecdce7fdd1d809ffd9a5a16e2086cc8bae54_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org3.yaml'
      discover: true 