name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: false

channels:
  - channelName: mychannel
    contracts:
    - id: basic2

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/6175b5029b90960a317434108c3b25c2a1cb9d3dff203c4c8761d3887e7251d1_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org1.json'
      discover: true

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/ed1290e800c0adcba53870e82a37d7559c870f92374c790fcd785aaaf938ccfd_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org2.json'
      discover: true

  - mspid: Org3MSP
    identities:
      certificates:
      - name: 'Admin1'
        admin: true
        clientPrivateKey:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/c54a5b918483118e764bc26832e9ed0dd0ce38e1b5da2e66ed744fe49ddabe44_sk'
        clientSignedCert:
          path: '../hlf-docker-swarm/test-network/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../hlf-docker-swarm/api-server/connection-org3.json'
      discover: true 
